# Generated by Django 4.2.20 on 2026-06-04 13:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('recruiter', 'HR-менеджер (рекрутёр)'), ('candidate', 'Кандидат (соискатель)')], default='candidate', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='Должность')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый отклик'), ('in_review', 'На рассмотрении'), ('interview', 'Собеседование'), ('offer', 'Оффер'), ('hired', 'Принят'), ('rejected', 'Отклонён')], default='new', max_length=20, verbose_name='Статус')),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Оценка соответствия (0–100)')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий рекрутёра')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отклика')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Отклик (заявка)',
                'verbose_name_plural': 'Отклики (заявки)',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=210, unique=True, verbose_name='Ссылка (slug)')),
                ('summary', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('body', models.TextField(verbose_name='Текст статьи')),
                ('author_name', models.CharField(default='Пресс-служба ЮНИТКОД', max_length=120, verbose_name='Автор')),
                ('published_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Статья/новость',
                'verbose_name_plural': 'Статьи и новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=80, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Город')),
                ('desired_salary', models.PositiveIntegerField(default=0, verbose_name='Желаемая зарплата, ₽')),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='Опыт работы, лет')),
                ('grade', models.CharField(choices=[('intern', 'Стажёр'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], default='junior', max_length=20, verbose_name='Грейд')),
                ('summary', models.TextField(blank=True, verbose_name='О кандидате')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название отдела')),
                ('head', models.CharField(blank=True, max_length=120, verbose_name='Руководитель')),
                ('headcount_plan', models.PositiveIntegerField(default=0, verbose_name='Плановая численность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(max_length=160, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Обращение (обратная связь)',
                'verbose_name_plural': 'Обращения (обратная связь)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Навык')),
                ('category', models.CharField(choices=[('lang', 'Язык программирования'), ('framework', 'Фреймворк/библиотека'), ('db', 'База данных'), ('tool', 'Инструмент/технология'), ('soft', 'Гибкий навык')], default='tool', max_length=20, verbose_name='Категория')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название источника')),
                ('kind', models.CharField(blank=True, help_text='например: джоб-борд, соцсеть, реферал', max_length=60, verbose_name='Тип')),
                ('cost_per_contact', models.DecimalField(decimal_places=2, default=0, help_text='Усреднённые затраты на одного привлечённого кандидата', max_digits=10, verbose_name='Стоимость привлечения, ₽')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник кандидатов',
                'verbose_name_plural': 'Источники кандидатов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название этапа')),
                ('order', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='Порядковый номер')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='Завершающий этап')),
            ],
            options={
                'verbose_name': 'Этап воронки',
                'verbose_name_plural': 'Этапы воронки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название вакансии')),
                ('grade', models.CharField(choices=[('intern', 'Стажёр'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], default='middle', max_length=20, verbose_name='Грейд')),
                ('salary_min', models.PositiveIntegerField(default=0, verbose_name='Зарплата от, ₽')),
                ('salary_max', models.PositiveIntegerField(default=0, verbose_name='Зарплата до, ₽')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('on_hold', 'Приостановлена'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], default='open', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание и требования')),
                ('city', models.CharField(blank=True, default='Москва', max_length=80, verbose_name='Город')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Удалённая работа')),
                ('opened_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата открытия')),
                ('planned_close', models.DateField(blank=True, null=True, verbose_name='Плановая дата закрытия')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='Фактическая дата закрытия')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='core.department', verbose_name='Отдел')),
                ('recruiter', models.ForeignKey(blank=True, limit_choices_to={'role': 'recruiter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный рекрутёр')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill', verbose_name='Навык')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Навык вакансии',
                'verbose_name_plural': 'Навыки вакансий',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='required_skills',
            field=models.ManyToManyField(related_name='vacancies', through='core.VacancySkill', to='core.skill', verbose_name='Требуемые навыки'),
        ),
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/%Y/%m/', verbose_name='Файл резюме')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='core.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'Резюме (файл)',
                'verbose_name_plural': 'Резюме (файлы)',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='Предлагаемая зарплата, ₽')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('status', models.CharField(choices=[('sent', 'Отправлен'), ('accepted', 'Принят'), ('declined', 'Отклонён'), ('expired', 'Истёк срок')], default='sent', max_length=20, verbose_name='Статус')),
                ('sent_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата отправки')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='core.application', verbose_name='Отклик')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hr', 'HR-интервью'), ('tech', 'Техническое'), ('final', 'Финальное')], default='hr', max_length=20, verbose_name='Тип')),
                ('scheduled_at', models.DateTimeField(verbose_name='Дата и время')),
                ('result', models.CharField(choices=[('scheduled', 'Назначено'), ('passed', 'Пройдено'), ('failed', 'Не пройдено'), ('no_show', 'Неявка')], default='scheduled', max_length=20, verbose_name='Результат')),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Балл (0–10)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.application', verbose_name='Отклик')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to=settings.AUTH_USER_MODEL, verbose_name='Интервьюер')),
            ],
            options={
                'verbose_name': 'Собеседование',
                'verbose_name_plural': 'Собеседования',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=120, verbose_name='Критерий')),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Балл (0–10)')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.interview', verbose_name='Собеседование')),
            ],
            options={
                'verbose_name': 'Оценка по критерию',
                'verbose_name_plural': 'Оценки по критериям',
                'ordering': ['interview', 'criterion'],
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Базовый'), (2, 'Уверенный'), (3, 'Продвинутый'), (4, 'Эксперт')], default=2, verbose_name='Уровень владения')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidate', verbose_name='Кандидат')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык кандидата',
                'verbose_name_plural': 'Навыки кандидатов',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(related_name='candidates', through='core.CandidateSkill', to='core.skill', verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='core.source', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись'),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.candidate', verbose_name='Кандидат'),
        ),
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.stage', verbose_name='Текущий этап'),
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='vacancyskill',
            constraint=models.UniqueConstraint(fields=('vacancy', 'skill'), name='uniq_vacancy_skill'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['status'], name='core_vacanc_status_c49e84_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidateskill',
            constraint=models.UniqueConstraint(fields=('candidate', 'skill'), name='uniq_candidate_skill'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['last_name', 'first_name'], name='core_candid_last_na_742bf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('candidate', 'vacancy'), name='uniq_candidate_vacancy'),
        ),
    ]
