# Generated by Django 4.2.20 on 2026-06-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applied_at'], name='app_applied_at_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='app_status_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['created_at'], name='cand_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['opened_at'], name='vac_opened_at_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['closed_at'], name='vac_closed_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidateskill',
            constraint=models.CheckConstraint(check=models.Q(('level__gte', 1), ('level__lte', 4)), name='cand_skill_level_range'),
        ),
    ]
