# Generated by Django 4.2.20 on 2026-09-04 19:10

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_industry_benchmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumefile',
            name='file',
            field=models.FileField(upload_to=core.models.resume_upload_path, verbose_name='Файл резюме'),
        ),
        migrations.CreateModel(
            name='ResumeParse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, verbose_name='Извлечённый текст')),
                ('normalized_text', models.TextField(blank=True, verbose_name='Нормализованный текст')),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Стаж по резюме, лет')),
                ('parser_version', models.CharField(default='1.0', max_length=10, verbose_name='Версия разборщика')),
                ('parsed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата разбора')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed', to='core.resumefile', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Результат разбора резюме',
                'verbose_name_plural': 'Результаты разбора резюме',
                'ordering': ['-parsed_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='От 0 до 100', max_digits=5, verbose_name='Оценка соответствия')),
                ('verdict', models.CharField(choices=[('recommended', 'Рекомендован'), ('review', 'На решение рекрутёра'), ('rejected', 'Не прошёл первичный отбор')], default='review', max_length=20, verbose_name='Решение')),
                ('matched_keywords', models.JSONField(blank=True, default=list, verbose_name='Найденные требования')),
                ('missing_keywords', models.JSONField(blank=True, default=list, verbose_name='Недостающие требования')),
                ('experience_match', models.BooleanField(default=False, verbose_name='Стаж соответствует')),
                ('reasons', models.JSONField(blank=True, default=list, verbose_name='Обоснование решения')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата расчёта')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='core.application', verbose_name='Отклик')),
            ],
            options={
                'verbose_name': 'Оценка соответствия',
                'verbose_name_plural': 'Оценки соответствия',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='ExternalVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('hh', 'hh.ru'), ('superjob', 'SuperJob'), ('avito', 'Avito Работа')], max_length=20, verbose_name='Площадка')),
                ('external_id', models.CharField(max_length=64, verbose_name='Идентификатор на площадке')),
                ('query', models.CharField(blank=True, max_length=200, verbose_name='Поисковый запрос')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на объявление')),
                ('salary_from', models.PositiveIntegerField(default=0, verbose_name='Зарплата от, р.')),
                ('salary_to', models.PositiveIntegerField(default=0, verbose_name='Зарплата до, р.')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='Ключевые слова требований')),
                ('loaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('imported_vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_origins', to='core.vacancy', verbose_name='Перенесена во внутренний реестр')),
            ],
            options={
                'verbose_name': 'Внешняя вакансия',
                'verbose_name_plural': 'Внешние вакансии',
                'ordering': ['-loaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 0), ('score__lte', 100)), name='match_score_range'),
        ),
        migrations.AddIndex(
            model_name='externalvacancy',
            index=models.Index(fields=['loaded_at'], name='ext_loaded_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalvacancy',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_external_source_id'),
        ),
    ]
